Compact menu design
mild-blue/even-better-quill pull request #3
Opened 2023-07-22 13:51 UTC by chirimiri22

2023-07-22 13:58 UTC, chirimiri22 commented
closes https://github.com/mild-blue/slp/issues/2972

2023-07-28 19:51 UTC, luborepka requested changes
Skvělá práce přesně takto jsem si to představoval

2023-07-28 19:51 UTC, luborepka commented on src/modules/better-table/modules/table-operation-menu.ts
> +      if (this.menuItems[name] && name !== "deleteTable") {
vím že je tady magic stringov až až ale když upravuješ kód snaž se je dávat do `const` prosím

2023-07-28 19:51 UTC, luborepka commented on src/modules/better-table/modules/table-operation-menu.ts
> +    this.actionSubTitle = options.actions && options.actions.text ? options.actions.text : DEFAULT_ACTION_SUBTITLE;
teraz je trochu divné že titulky k buttonom nastavujem cez key `items` ale k nadpisu sekcie sa dostanem cez `actions`. Lepší by to bylo mít všechno pod `actions` ale to je spousta refactoringu takže bych spíš tohle `actions` přidal pod `items`

2023-07-29 11:19 UTC, chirimiri22 commented
nějak takhle?

2023-07-31 19:17 UTC, luborepka approved these changes
Přesně super

2023-07-31 19:17 UTC, merged