Add custom remove formatting function so that it doesn't break tabel
mild-blue/even-better-quill pull request #7
Opened 2023-08-26 22:36 UTC by chirimiri22

### Goal
Fix bug that is caused by clicking `remove formatting` when selected text is in a table. 

### Background

The table breaks completely by this bug, see https://github.com/mild-blue/slp/issues/3417

### Implementation

When `BetterTable` module is used, there's a custom handler added for formatting so that the table remains the same. The new implemented function just does formatiing for text not for lines. 

This cause that line formatting like bullets and ordered won't be changed by this handler and user has to do it manually. But creating of an ordered list in tables is broken anyway, see https://github.com/mild-blue/slp/issues/3417#issuecomment-1694499120

### Testing

Manually

2023-09-13 15:17 UTC, tomaspavlin reviewed
Může na tohle kouknout @luborepka ?

2023-09-13 15:17 UTC, tomaspavlin commented on src/modules/better-table/quill-better-table.ts
> +  }
Tady bych řekl, že ti to třeba neresetuje velikost textu nebo zalinkování, ne? Podle mě mazání formátování tímhle způsobem nemůže fungovat nikdy 100%.

2023-09-18 09:45 UTC, luborepka requested changes

2023-09-18 09:45 UTC, luborepka commented on src/modules/better-table/quill-better-table.ts
> +    toolbar.addHandler("clean", () => this.removeTextFormatting());
Nejlepší by bylo vložit filter do tý původní funkce. To nevím jestli je nějak rozumě možné bez zásahu do core. 

Takže druhá nejlpší možnost je prostě zmazat v delte atributy všemu kromě tabulky. (obrázky by to měli přežít tam se zmažej jenom fixed width). Tohle by pak mělo vyřešit i to když nám tam někdo vloží třeba list nebo něco jiného.

2023-09-24 22:37 UTC, chirimiri22 commented
bavili jsme se s  @kubantjan že to nebude mít smysl předělávat, když bych to vlastně musela vyřešit úplně jinak od začátku. tenhle úkol jsem myslím vytáhla z Todo bcuketu těsně před tím, než se řeklo, že se vývoj editoru freezne.

2023-09-24 22:37 UTC, closed without merging